name = "LocalAncestry"
uuid = "9c717bbe-74a8-4a1b-8702-c9261a6bba1a"
version = "0.9.0"
authors = ["Bjarke G. Poulsen", "Emre Karaman"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
VariantCallFormat = "28eba6e3-a997-4ad9-87c6-d933b8bca6c1"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
Dates = "1.11.0"
GZip = "0.6.2"
OrderedCollections = "1.8.0"
Tables = "1.12.0"
VariantCallFormat = "0.5.6"
julia = "1.11.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
